language: php
php:
- '7.1'
script:
- 
before_deploy:
- npm install --silent
- npm run build:production
- mkdir -p dewp-planet-feed
- rsync -rav --exclude-from='.rsync-exclude' --delete-excluded ./ dewp-planet-feed
- zip -r dewp-planet-feed-$TRAVIS_TAG.zip dewp-planet-feed/
- rm -rf dewp-planet-feed
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: E5/yFkq427zyXzdEh00WQqS7d6bwSx6tH9sgSV6GFOqd9aeVkeRM52NPDiYJO4qN9cu4rn2X4ACJAY8imrNf2mGLWVYiLQMBiwV6ENUClxcdtclYpw8wdxphyLH5NGoSvjR895QBObOYSXA/Nr33NSPH9dPmiEWo2/dfx5UijWZ0dGD3V3KmOyhcqGEp4QdYORwlGzALf9GkjgAKeAu9GiZ2v7gPcLq7iV75p6x7degkSVfcpjdUgU3ZSmGiIXzL8Ncb8XhDxUD7XoSIR5BDRp1ryGguCVaIKcRocFxmpPpLXdiHWpzp/Zk1u+u0R2lEo2xnp/28llw3hfKdpRiGVMNbMzCGvn40oPLR8EgfQcMACGvi9LXfdkJrsGCNuODrAR7skI0M5FsgzFlxdW/UEdZBdlWvKNvRRMI2jq50jpQRTYcS3b4GeZqk7zqYbUDHHJZyiq4NL/pZby6FqvfbvfFw7/kiUIJPn/5VB69/e9ztDlaEUXOXF5DDX8bfz1GM1yU3ToLYHfq4fpG33/e2rW6+wphG32rcYw4sFFOetMe8kWG0KJDmboMd93Kep+1x4iUf/84NY8UUiN9M9AEfVbZWcRhFXVWVGkOVZ8Eosw307RRiNJXbQWlvy5VDiW14l9VsLgdgFgC/cEm7KWt7alDM6KPz4izhqxvvd+MxusQ=
  file: dewp-planet-feed-$TRAVIS_TAG.zip
  on:
    repo: deworg/dewp-planet-feed
    tags: true
